### ISSUE TITLE
Why aren't I seeing the background image?

### ISSUE THREAD

**Issue by kevinsimper** [camel-chased/editor-background#11]
i just see this, and haven't done anything other than choosing the image?

![image](https://cloud.githubusercontent.com/assets/1126497/10398051/2e935f1a-6eab-11e5-926f-f6bb11a7d28a.png)

**Comment by camel-chased** [comment]
click ctrl+shift+e and paste image url here

W dniu 2015-10-09 o 17:29, Kevin Simper pisze:

**Comment by kevinsimper** [comment]
/Users/kevinsimper/Dropbox/Blackbeard/blackbeard_logo_white.png

![blackbeard_logo_white](https://cloud.githubusercontent.com/assets/1126497/10398650/954e5950-6eae-11e5-9ed2-04d5bf035b99.png)

**Comment by kevinsimper** [comment]
![image](https://cloud.githubusercontent.com/assets/1126497/10398714/dd0c878a-6eae-11e5-8de8-3a0875a56a5c.png)

**Comment by camel-chased** [comment]
you have white image on white background :)
i will color background of backgound image in the next patch so you can 
set backgound color of background image

W dniu 2015-10-09 o 17:53, Kevin Simper pisze:

**Comment by camel-chased** [comment]
wow, a lot of backgrounds you have there ;)
i will fix this too, but this is not reason for not seeing white on white
but thanks for report

**Comment by kevinsimper** [comment]
Nice!

**Comment by kevinsimper** [comment]
Can't it just use the normal background color, that the theme already has choosen?

**Comment by camel-chased** [comment]
ok, you will be able to choose, if you want standard theme color or any 
other color of your choice

W dniu 2015-10-09 o 18:01, Kevin Simper pisze:

**Comment by camel-chased** [comment]
![beard](https://cloud.githubusercontent.com/assets/10367616/10401745/40c36da4-6ec1-11e5-9df2-e16157ed684a.jpg)
try now

**Comment by camel-chased** [comment]
if some issues occur while using new ver just reopen this topic or create new one from stacktrace
have a good day!

**Comment by kevinsimper** [comment]
Better, but there is a bug that slow atom down to its knees, related to this
![image](https://cloud.githubusercontent.com/assets/1126497/10402193/23b18f54-6ec4-11e5-881d-66871f9eb240.png)

**Comment by camel-chased** [comment]
i think that i fixed this in latest release 1.2.8
which ver do you have?

**Comment by kevinsimper** [comment]
Yes, it seems that it was solved, but there is another problem :/
![background](https://cloud.githubusercontent.com/assets/1126497/10402661/f6f2f9be-6ec6-11e5-8aa6-cd3feb30d629.gif)

**Comment by camel-chased** [comment]
this is normal... just override of css
it must be that way
if you want to know where each body are declared just click on <style>...</style> to see if it is editor-background "instances" of css or other plugins/themes
just css that is declared later(or !impotant) overrides previous declaration

**Comment by camel-chased** [comment]
if you want to be happy atom/web user just don't look at source code!
if everything suppose to be ok , don't dig it ;) it's ok to be not exactly perfect
if some weird things happening in your atom, don't bother
unless you can't work  on it, this rarely happens
;)
