### ISSUE TITLE
"Editor-background is only available after you open some files"

### ISSUE THREAD

**Issue by saghm** [camel-chased/editor-background#12]
When I press ctrl-shift-E like the settings menu says to, I just get a popup message saying "Editor-background is only available after you open some files".  I've tried using this shortcut both in the settings menu and when I have a file open, and in neither case does a window pop up that lets me do anything.

I'm on a Macbook running Yosemite; does this package work on OS X?

**Comment by camel-chased** [comment]
it should work on mac too hmm
maybe you are opening wrong file :P
but it should work on any source code file hmmm
I know that README files are troublesome for editor-background
which kind of file you are opening?
try to create new temp.js (javascript) file and then press ctrl+shift+e
maybe there is another type of file that editor-background doesn't sees as source code file
tell me what extension do you opening and then I will try to figure out what's happening
thanks for report

**Comment by saghm** [comment]
It started working for me earlier today; I think another package I use that hides the tree view on the left side might have been interfering with it, since when I unhid the tree view and then hid it again, suddenly my background showed up, and then I could open the settings window fine. Since then, it's been working fine, hopefully I won't develop sent issues on further use.

Thanks for taking the time to respond! I'm really liking the package so far, and I'm looking forward to spending more time playing around with it.
