### ISSUE TITLE
Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided val...

### ISSUE THREAD

**Issue by zawata** [camel-chased/editor-background#13]
[Enter steps to reproduce below:]

1. Try To Animate youtube video
2. Cry

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Pro
**Thrown From**: [editor-background](https://github.com/camel-chased/editor-background) package, v1.2.11

### Stack Trace

Uncaught TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'

```
At /C:/Users/Zach/.atom/packages/editor-background/lib/animation.coffee:147

TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(HTMLImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap)'
  at TypeError (native)
  at Animation.drawFrame (C:\Users\Zach\.atom\packages\editor-background\lib\animation.coffee:96:12)
  at Animation.animate (C:\Users\Zach\.atom\packages\editor-background\lib\animation.coffee:102:8)
  at Animation.imageLoaded (C:\Users\Zach\.atom\packages\editor-background\lib\animation.coffee:56:8)
  at HTMLImageElement.<anonymous> (C:\Users\Zach\.atom\packages\editor-background\lib\animation.coffee:63:20)

```

### Commands

```
     -8:04.4.0 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "ice-cold-syntax"
    ],
    "destroyEmptyPanes": false
  },
  "editor-background": {
    "box3d": {},
    "image": {
      "url": "C:/Users/Zach/.atom/background.png",
      "overlayColor": {
        "red": 0,
        "green": 0,
        "blue": 0,
        "alpha": 1
      },
      "style": "background:radial-gradient(rgba(0,0,0,0) 100%,rgba(0,0,0,0.75));",
      "repeat": "repeat"
    },
    "other": {
      "treeViewOpacity": 1
    },
    "text": {
      "expand": 6,
      "blur": 29,
      "opacity": 43
    },
    "video": {
      "animationSpeed": 100,
      "opacity": 50,
      "endTime": "60s",
      "youTubeURL": "www.youtube.com/watch?v=ZGHVX6pDVKc",
      "playAnimation": true
    },
    "blurRadius": 0
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
build, v0.47.0
color-picker, v2.0.13
editor-background, v1.2.11
ice-cold-syntax, v0.1.0
json-schema, v0.1.15
linter, v1.8.1
nucleus-dark-ui, v0.6.5
omnisharp-atom, v0.25.2

# Dev
No dev packages
```

**Comment by zawata** [comment]
I attempted to find the source of the error but I don't know coffee and wasn't able to get very far...

**Comment by camel-chased** [comment]
do you have specified startTime ?

**Comment by zawata** [comment]
1. yes(0s)
2. yes but it played through the animation until it hit that point(whatever the broken point of the animation was)
3. no but it does freeze and stop itself(which im almost certain is the problem(not enough pictures for the index?))
4. yes, i find it the best way to use it.

also note that shortly after this error i tried to deleted the saved video and try again and the then it started crashing atom not the package

i managed to get it to run after turn the resolution down and only using 10 seconds

also bravo with this package, even without the youtube feature this package rocks

**Comment by zawata** [comment]
pretty sure the issue was a problem with internet connection or something
