### ISSUE TITLE
Stucking at Frame 0

### ISSUE THREAD

**Issue by TheCherry** [camel-chased/editor-background#18]
Its stucking after add a video URL

```
Getting Frame: 0
Please be patient.
```

**Comment by camel-chased** [comment]
hmmm
with every video?
it must be youtube of course
length of the fragment you want to dowload should be about 1min or less

**Comment by TheCherry** [comment]
yes every video, did try much configs. And yes I used youtube, length 
tried from 10-60sec.
Its Download the Video, I can find it in the Directory but its don't 
start to decode the fraps, the image directory is complete empty.

I use Ubuntu 14.04 by the way.

Am 11.12.2015 um 13:39 schrieb camel-chased:

**Comment by camel-chased** [comment]
maybe this is something with files/premissions/path to files
maybe some special characters in the file name
getting frames means that video is downloaded but maybe corrupted or something
do you have some free space on drive with atom? :)
i really don't know what is happening, everything should work

**Comment by TheCherry** [comment]
So reinstall it and tried 2 Videos:
https://www.youtube.com/watch?v=hFHYyy8K-DI
https://www.youtube.com/watch?v=AwXXxnpddNg
Both same problem.

Permissions are fine:
```
drwxrwxr-x 2 myuser myuser       4096 Dez 11 14:28 AwXXxnpddNg_images
-rw-rw-r--   1 myuser myuser 1377381 Dez 11 14:27 AwXXxnpddNg.mp4
drwxrwxr-x 2 myuser myuser       4096 Dez 11 14:29 hFHYyy8K-DI_images
-rw-rw-r--   1 myuser myuser   623899 Dez 11 14:28 hFHYyy8K-DI.mp4
```
I can open a mp4 file with VLC-Player, without errors.
Have enough free space (700G+)

Can I send you any Log files?

**Comment by camel-chased** [comment]
on my machine it works :)
paste logs here

**Comment by TheCherry** [comment]
sry, but there I do find the log files from atom?

**Comment by camel-chased** [comment]
get system logs
/var/log
if there is a problem with files it shoulg go to system logs

**Comment by TheCherry** [comment]
```
sudo grep -rE "editor-background" /var/log/*
sudo grep -rE "hFHYyy8K-DI" /var/log/*
sudo grep -rE "_images" /var/log/*
```
Nothing ....

**Comment by camel-chased** [comment]
do you reinstalled atom? complete remove folder?

**Comment by TheCherry** [comment]
Did try a clean config
```
export ATOM_HOME=$HOME/.atom2/ atom
```
There its work perfectly.
I found now the JS Console with logs, but no error is present here (in my default environment)
```
getting video info
youtube.coffee:123 formats finished Object {133: Object, 134: Object, 135: Object, 160: Object, 298: Object, 299: Object}
editor-background.coffee:553 get video info ready
editor-background.coffee:473 choose format?
editor-background.coffee:560 we chosen format 299
```

It seems that this is a conflict with a another package, that is my package list:
```
atom-debugger/                 bottom-dock/                   flex-tool-bar/                 linter/                        minimap-bookmarks/             seti-syntax/                   tool-bar/
atom-gdb/                      browser-plus/                  git-diff-details/              linter-flake8/                 python-nosetests/              seti-ui/                       wombat-dark-syntax/
atom-update/                   clock/                         git-plus/                      linter-manager/                python-yapf/                   seti-ui-red/                   
autocomplete-plus-python-jedi/ color-picker/                  git-projects/                  linter-python-pep257/          remote-edit/                   set-syntax/                    
bitcoin-status-bar/            editor-background/             hex/                           merge-conflicts/               rest-client/                   terminal-plus/                 
bookmark-panel/                file-bookmark/                 highlight-selected/            minimap/                       script/                        todo-manager/
```

**Comment by TheCherry** [comment]
Okay okay, that's annoying. The error is more then sadly ...
Did configure this:
Start: 0
End: 10
Instant of 0s and 10s
... -.-*

**Comment by camel-chased** [comment]
i will checkout this tommorow on ubuntu but i don't think I'll have the same error

**Comment by camel-chased** [comment]
on my kubuntu also everything works
![kubuntu](https://cloud.githubusercontent.com/assets/10367616/11749371/96b2c51e-a02d-11e5-8c4d-5ad37e5fe478.png)

**Comment by camel-chased** [comment]
![kubuntu1](https://cloud.githubusercontent.com/assets/10367616/11749457/2600aaa6-a02e-11e5-8063-27a228e51f17.png)

**Comment by camel-chased** [comment]
no body else have similar issue so closing
I don't have time now to play with it
