### ISSUE TITLE
Shadow highlight mismatch

### ISSUE THREAD

**Issue by TG-KK** [camel-chased/editor-background#19]
This has started appearing since atom 1.3.0 AFAIR

Background shadow highlight doesn't update accurately on text area

Kind of flaky scenario. It's not always the case. Sometimes its correct, other times its not.

Easily replicable if you scroll slowly.

![shadow highlight mismatch](https://cloud.githubusercontent.com/assets/6836944/11814066/db7654fa-a36a-11e5-9f4f-a64994b2de2d.PNG)

Also, might be related...for new file, shadow remains in the editor, until I start typing

![new file highlight](https://cloud.githubusercontent.com/assets/6836944/11814067/db87c80c-a36a-11e5-9b61-444bfc018bb7.PNG)

**Comment by camel-chased** [comment]
yes, something has changed in 1.3
I am aware of it
thanks for report anyway

**Comment by camel-chased** [comment]
this is problem of (activeEditor).getVisibleRowRange is incorectly implemented in atom since 3.0

**Comment by camel-chased** [comment]
fixed in 1.2.17 :)
