### ISSUE TITLE
Seems not working?

### ISSUE THREAD

**Issue by lovesnow10** [camel-chased/editor-background#23]
I'm using Atom1.7.0 latest version on osx, and it seems that the package is not working. Since I tried to specify the image url both locally and by a super link, but nothing happened. Is there a instruction of usage?

**Comment by camel-chased** [comment]
You must open editor-background custom config window.
On windows it is ctrl+shift+e.
On mac i don't know but something with cmd key :)
There will be apply button in this window.
Maybe it will work, maybe not :)
If not you can open dev tools in atom and copy error you have here

W dniu 2016-04-14 o 23:40, Shana pisze:

**Comment by lovesnow10** [comment]
Do you mean "toggle editor background"? I tried this, but atom told me "Editor-background is only available after you open some files" though indeed I've opened some files.
![image](https://cloud.githubusercontent.com/assets/10862781/14554500/c4fdb672-02ed-11e6-98f3-58d88a3006b0.png)

**Comment by lovesnow10** [comment]
Oh, It works when I open a Project... So why not make it work at any time, is there some technique problems?

**Comment by cbuschardt** [comment]
Yeah, I've had the same issue.  It won't enable until I open the project bar and close it.  Very odd.

**Comment by HaykoKoryun** [comment]
Also, if Atom starts with the Tree View on the right the background is not initialised. However bringing the Tree View back to the left (and then to the right) initialises it.

**Comment by camel-chased** [comment]
there are just few events in atom, eb uses them all but it is not enough unfortunately
I can't do much without events, so my hands are tied
There will be some gotchas here and there if we want to have good performance in eb too
I will recheck what I can do to improve user experience in couple of days so maybe I find some better approaches to current problems, thanks

**Comment by camel-chased** [comment]
is this problem still exist on 1.2.29 ?

**Comment by camel-chased** [comment]
1.2.30 should fix this issue.
Background of the treeview will be original on toggle, because I don't have time now to separate treeview initialization logic outside of main initialization. Maybe some of you will do this is open source :)
