### ISSUE TITLE
Getting Shadow DOM error message

### ISSUE THREAD

**Issue by Mootly** [camel-chased/editor-background#29]
As of this morning, or at least very recently, getting the following message for this package:

> Use Shadow DOM option must be enabled to run editor-background.

Shadow DOM is now on by default with no option to disable, so perhaps related to atom.io progressively removing all logic to disable the Shadow DOM?

**Comment by Xamb** [comment]
Hi.... I have the same issue today.... yesterday it was all fine, but it seems atom had an update and i cannot set a background image in the editor... it shows Use Shadow DOM option must be enabled to run editor-background., but I cannot find where is that option

**Comment by Mootly** [comment]
Quick fix:
In `[path to atom]\packages\editor-background\lib\editor-background.coffee`

Line 29: `shadowDomEnabled = atom.config.get 'editor.useShadowDOM'`

Add the following right below it:
`shadowDomEnabled = true`

Forces the check to true without mucking about in the conditionals that use the flag below.

**Comment by Xamb** [comment]
It works !!! Thanks Mootly
