### ISSUE TITLE
Installing “editor-background@1.2.27”

### ISSUE THREAD

**Issue by fahmiansori** [camel-chased/editor-background#31]
npm WARN engine request@2.78.0: wanted: {"node":">= 4"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm ERR! fetch failed https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.7.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/es6-symbol/-/es6-symbol-3.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.7.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/es6-symbol/-/es6-symbol-3.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.7.tgz
npm ERR! fetch failed https://registry.npmjs.org/es6-symbol/-/es6-symbol-3.1.0.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Muhamad Fahmi Ansori\\AppData\\Local\\atom\\app-1.2.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Muhamad Fahmi Ansori\\AppData\\Local\\atom\\app-1.2.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Muhamad Fahmi Ansori\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Muhamad Fahmi Ansori\\.atom\\.apmrc" "install" "C:\\Users\\MUHAMA~1\\AppData\\Local\\Temp\\d-116107-7208-1e9po3f\\package.tgz" "--target=0.34.0" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3

npm ERR! fetch failed with status code 503
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by camel-chased** [comment]
I don't have time now. If you want, you can make pull request to fix this - it is open source :)

**Comment by camel-chased** [comment]
is this error editor-background related?
more info needed, operating system, version of eb, version of atom etc
if you give more info about this error then i will reopen this issue
