### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by bigfantastic** [camel-chased/editor-background#34]
Hello!I am Weichen Wang. I am sure that I open a file.But it says that editor-background is only available after I open some files.
I can't use it to show my background.I feel so bad.
Please help me!Thank you!

**Comment by neuronetpl** [comment]
I don't know why. In my computer everything work as expected ;)
tell me more, what is your system? what version of atom do you use? what plugins do you have installed? more... more... more....

**Comment by camel-chased** [comment]
I don't know why. In my computer everything work as expected ;)
tell me more, what is your system? what version of atom do you use? what plugins do you have installed? more... more... more....

**Comment by camel-chased** [comment]
closing because of no response
