### ISSUE TITLE
Possible options for images background position?

### ISSUE THREAD

**Issue by THCloud** [camel-chased/editor-background#46]
default value is center, but i write follow options, they don't work:
left
right
center left
center right

and background size I choose manual. it is a picture with [900*580px](http://game.gtimg.cn/images/tlbb/cp/a20170901wmjh/c1-role-03.png)

Mac. Atom 1.20

**Comment by THCloud** [comment]
these options works on windows。

**Comment by camel-chased** [comment]
this is CSS related and EB cannot do anything with it.
[mdn](https://developer.mozilla.org/pl/docs/Web/CSS/background-position)
[w3](https://www.w3schools.com/cssref/pr_background-position.asp)
