### ISSUE TITLE
Background image dont work on windows

### ISSUE THREAD

**Issue by Pllet** [camel-chased/editor-background#6]
for what i could see, the background image is not loaded becouse the image url is interpreted wrong, for example D:/docs/img.jpg the plugin loads D:/docsimg.jpg, so in the background only appears a white radial gradient.

**Comment by Hellbabine** [comment]
I have the same problem, the easy solution is to upload your image somewhere on internet, and from what i've experienced, html work fine. Still, it would be great to adress the problem, it would be more practical for changing image then to have to upload it everytime

**Comment by camel-chased** [comment]
yes, problem is in file path, i'm working on linux so "on my machine everything works" :)
next update will fix this, thanks for report
