### ISSUE TITLE
Uncaught TypeError: Cannot read property 'visible' of undefined

### ISSUE THREAD

**Issue by igorbrandao** [camel-chased/editor-background#7]
[Enter steps to reproduce below:]

1. Just press ctrl + shift + e to open settings anywhere on atom and this gets thrown.

**Atom Version**: 1.0.1
**System**: Windows 8.1
**Thrown From**: [editor-background](https://github.com/camel-chased/editor-background) package, v1.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'visible' of undefined

```
At C:\Users\Igor\.atom\packages\editor-background\lib\editor-background.coffee:989

TypeError: Cannot read property 'visible' of undefined
  at Object.module.exports.EditorBackground.toggle (C:\Users\Igor\.atom\packages\editor-background\lib\editor-background.coffee:989:22)
  at atom-workspace.atom.commands.add.editor-background:toggle (C:\Users\Igor\.atom\packages\editor-background\lib\editor-background.coffee:198:39)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Program Files\Atom 1.0.1\resources\app.asar\src\command-registry.js:241:29)
  at C:\Program Files\Atom 1.0.1\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Program Files\Atom 1.0.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Program Files\Atom 1.0.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Program Files\Atom 1.0.1\resources\app.asar\src\window-event-handler.js:177:20)

```

### Commands

```
     -0:12.5.0 settings-view:uninstall-packages (atom-text-editor.editor.is-focused)
     -0:04.6.0 editor-background:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "editor-background": {
    "box3d": {
      "shadowOpacity": 100,
      "depth": 2000
    },
    "image": {
      "backgroundSize": "100%",
      "manualBackgroundSize": "100%",
      "overlayColor": {
        "red": 0,
        "green": 0,
        "blue": 0,
        "alpha": 1
      },
      "opacity": 14
    },
    "other": {
      "transparentTabBar": false,
      "treeViewOpacity": 80
    },
    "text": {
      "blur": 0,
      "expand": 0,
      "opacity": 0
    },
    "video": {
      "youTubeURL": "https://www.youtube.com/watch?v=rpWrtXyEAN0",
      "endTime": "1000"
    },
    "blurRadius": 0
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.9
editor-background, v1.0.1
language-groovy, v0.4.0
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by Falieson** [comment]
I think I figured out why this error is happening, at least for me! I installed it and tweaked the settings and nothing worked - I was disappointed and thought the plugin was broken. It's been probably an hour, but I opened up the sidebar revealing my project folders and tada! everything, even the editor window now works!

**Comment by martin-damien** [comment]
I have the same issue:

**OS:** GNU/Linux (Ubuntu 15.04)
**Atom:** 1.0.3

I have the same error using Image or Youtube.

**Comment by martin-damien** [comment]
Just found the reason why!

This error is raised when you have `nuclide-file-tree` installed. The two extensions are not compatible.

**Comment by lalomartins** [comment]
I have this problem and I don't have `nuclide-file-tree`.

**Comment by lalomartins** [comment]
Oh dear. After a few minutes, my theme switched of its own accord to Ugly™, and now the package works O.o I wonder what happened there

**Comment by lalomartins** [comment]
When I start Atom, the background doesn't kick in. Then after a few minutes, it pops up this error. If I wait a few more minutes and press the keybinding, it does work.

Sorry but as it is, it's not really usable :-/

**Comment by Falieson** [comment]
yeah, I uninstalled and am using dark material theme.

**Comment by ScottBeeson** [comment]
I got this error after setting a youtube video and then trying to set it back to an image.  Toggling the treeview did make the error go away and the background image came back.

**Comment by camel-chased** [comment]
hmmm
i think that is because of other themes/plugins uses same resources
it is hard to guess which theme/plugin uses same resources in dom tree
every plugin/theme is working on the same body so there will be some conflicts
i cannot check all the plugins and try to tweak editor-background to work with them
editor-background change what you see and this is risky if you have other plugins and non standard themes that have a lot of weird things going on in the dom tree
try to disable some plugins and check what is in conflict

**Comment by camel-chased** [comment]
sorry, problem of "visible of undefined" shows up when you have no editor open, i must fix this
but previous message is also true

**Comment by camel-chased** [comment]
fixed in new version
