### ISSUE TITLE
Configuration options disappears

### ISSUE THREAD

**Issue by martin-damien** [camel-chased/editor-background#8]
**OS:** Ubuntu 15.04
**Atom:** 1.0.3

When I first install `editor-background` I can edit everything in the settings.
But once I close the settings panel and I try to re-open it, I can only modify the fields where I put somethings (the other fields are hidden).

**Comment by camel-chased** [comment]
You talking about default settings panel from atom?
yeah it some weird things going there
i recommend to use a ctrl+shift+o  for popup panel with more controls

**Comment by martin-damien** [comment]
Yes, that is. It is very disapointing. Maybe you should just put a message to use `Ctrl+Shift+E` instead.

Thant you very much for this awesome extension :)
